experts_db:
  id: 1
  conn_name: experts DB
  type: postgres
  host: host.docker.internal
  port: 5432
  dbname: simulation2
  user: postgres
  password: a
  schema: public
schematest:
  id: 2
  conn_name: schemaTest
  type: postgres
  host: host.docker.internal
  port: 5432
  dbname: res
  user: postgres
  password: a
  schema: SC1
mysqltest:
  id: 3
  conn_name: mysqltest
  type: mysql
  host: host.docker.internal
  port: 3306
  dbname: stage2a
  user: root
  password: aaaa
  schema: public
